sudo: required
# Require Travis to use Docker
services:
    - docker
env:
    global:
        - SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    # This is for travis to use the encrypted file
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
    # Download and install Google Cloud CLI
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    # Add auth tokens with CLI
    - gcloud auth activate-service-account --key-file service-account.json
    # Setup google cloud config and cluster to use
    - gcloud config set project multi-k8s-281515
    - gcloud config set compute/zone us-east1-b
    - gcloud containers clusters get-credentials multi-cluster
    # Login to docker hub
    - echo $DOCKER_PW | docker login -u $DOCKER_ID --password-stdin
    # Build container for testing app
    - docker build -t $DOCKER_ID/react-test -f ./client/Dockerfile.dev ./client

scripts:
    # Run app test
    - docker run -e CI=true $DOCKER_ID/react-test npm test

deploy:
    provider: script
    script: bash ./deploy.sh
    on:
        branch: master
