apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: lawrencecymbura-com-tls
spec:
    secretName: lawrencecymbura-com
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
        commonName: lawrencecymbura.com
        dnsNames:
            - lawrencecymbura.com
            - www.lawrencecymbura.com
        acme:
            config:
                - http01:
                      ingressClass: nginx
                  domains:
                      - lawrencecymbura.com
                      - www.lawrencecymbura.com
